package santa.runtime

import santa.runtime.value.*
import kotlinx.collections.immutable.persistentListOf
import kotlinx.collections.immutable.toPersistentList

/**
 * Built-in functions for santa-lang.
 *
 * These functions are called from generated bytecode via static dispatch.
 */
object Builtins {

    /**
     * size(collection) - Returns the size of a collection.
     */
    @JvmStatic
    fun size(value: Value): Value = when (value) {
        is ListValue -> IntValue(value.size().toLong())
        is SetValue -> IntValue(value.size().toLong())
        is DictValue -> IntValue(value.size().toLong())
        is StringValue -> IntValue(value.graphemeLength().toLong())
        else -> throw SantaRuntimeException("size: expected collection, got ${value.typeName()}")
    }

    /**
     * first(collection) - Returns the first element or nil.
     */
    @JvmStatic
    fun first(value: Value): Value = when (value) {
        is ListValue -> value.get(0)
        is StringValue -> {
            val grapheme = value.graphemeAt(0)
            if (grapheme != null) StringValue(grapheme) else NilValue
        }
        else -> throw SantaRuntimeException("first: expected List or String, got ${value.typeName()}")
    }

    /**
     * rest(collection) - Returns all elements except the first.
     */
    @JvmStatic
    fun rest(value: Value): Value = when (value) {
        is ListValue -> if (value.size() <= 1) {
            ListValue(persistentListOf())
        } else {
            value.slice(1, value.size())
        }
        is StringValue -> StringValue(value.graphemeSlice(1, value.graphemeLength()))
        else -> throw SantaRuntimeException("rest: expected List or String, got ${value.typeName()}")
    }

    /**
     * push(collection, value) - Returns a new collection with value appended.
     */
    @JvmStatic
    fun push(collection: Value, value: Value): Value = when (collection) {
        is ListValue -> ListValue(collection.elements.add(value))
        else -> throw SantaRuntimeException("push: expected List, got ${collection.typeName()}")
    }

    /**
     * int(value) - Converts value to integer. Returns 0 for unparseable strings.
     */
    @JvmStatic
    fun int(value: Value): Value = when (value) {
        is IntValue -> value
        is DecimalValue -> IntValue(value.value.toLong())
        is StringValue -> {
            val cleaned = value.value.trim().replace("_", "")
            IntValue(cleaned.toLongOrNull() ?: 0L)
        }
        is BoolValue -> IntValue(if (value.value) 1L else 0L)
        else -> throw SantaRuntimeException("int: cannot convert ${value.typeName()} to Integer")
    }

    /**
     * type(value) - Returns the type name as a string.
     */
    @JvmStatic
    fun type(value: Value): Value = StringValue(value.typeName())

    /**
     * keys(dict) - Returns the keys of a dictionary as a list.
     */
    @JvmStatic
    fun keys(value: Value): Value = when (value) {
        is DictValue -> value.keys()
        else -> throw SantaRuntimeException("keys: expected Dictionary, got ${value.typeName()}")
    }

    /**
     * values(dict) - Returns the values of a dictionary as a list.
     */
    @JvmStatic
    fun values(value: Value): Value = when (value) {
        is DictValue -> value.values()
        else -> throw SantaRuntimeException("values: expected Dictionary, got ${value.typeName()}")
    }

    /**
     * abs(n) - Returns the absolute value.
     */
    @JvmStatic
    fun abs(value: Value): Value = when (value) {
        is IntValue -> IntValue(kotlin.math.abs(value.value))
        is DecimalValue -> DecimalValue(kotlin.math.abs(value.value))
        else -> throw SantaRuntimeException("abs: expected Integer or Decimal, got ${value.typeName()}")
    }

    /**
     * Lookup table for built-in functions by name.
     * Maps name -> (arity, function reference)
     */
    val registry: Map<String, BuiltinInfo> = mapOf(
        "size" to BuiltinInfo(1, Builtins::size),
        "first" to BuiltinInfo(1, Builtins::first),
        "rest" to BuiltinInfo(1, Builtins::rest),
        "push" to BuiltinInfo(2, Builtins::push),
        "int" to BuiltinInfo(1, Builtins::int),
        "type" to BuiltinInfo(1, Builtins::type),
        "keys" to BuiltinInfo(1, Builtins::keys),
        "values" to BuiltinInfo(1, Builtins::values),
        "abs" to BuiltinInfo(1, Builtins::abs),
    )
}

/**
 * Info about a built-in function.
 */
data class BuiltinInfo(
    val arity: Int,
    val function: Any, // KFunction reference
)
